### ISSUE TITLE
bug!!

### ISSUE THREAD

**Issue by brinkqiang** [seanmiddleditch/gha-setup-vsdevenv#11]
```
name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: build
        # working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          cmake --version
          cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build --config $BUILD_TYPE
      - name: Test
        # working-directory: ${{runner.workspace}}
        shell: bash
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
  win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: seanmiddleditch/gha-setup-vsdevenv@v3

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: build
        # working-directory: ${{runner.workspace}}
        shell: cmd
        run: |
          cmake --version
          cmake -B build -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build --config $BUILD_TYPE
      - name: Test
        # working-directory: ${{runner.workspace}}
        shell: cmd
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
```

if you set it like this

cmake --build build --config $BUILD_ TYPE

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of $BUILD_TYPE|x64. [D:\a\dmtimer\dmtimer\build\ZERO_CHECK.vcxproj]
Error: Process completed with exit code 1.
```

will prompt

if you set it like this

cmake --build build

the output is the debug version

can't set $BUILD_ TYPE
