### ISSUE TITLE
Can't re-setup the environment properly.

### ISSUE THREAD

**Issue by dabrahams** [seanmiddleditch/gha-setup-vsdevenv#23]
In my workflow I had:

```
      - uses: seanmiddleditch/gha-setup-vsdevenv@main
      
      # ...a bunch of steps...
      
      - uses: seanmiddleditch/gha-setup-vsdevenv@main
        with:
          host_arch: amd64
          toolset_version: 14.37.32822
          components: 'Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64;Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64'
          arch: arm64

      # ...more steps...
     
```

But the tools didn't work right for "more steps".  I'm having to 

```
      # setup-vsdevenv doesn't properly overwrite an earlier setup.
      - name: save Windows environment
        if: ${{ matrix.os == 'windows-latest' }}
        run: Get-ChildItem env: | Export-CliXml ./pre-vsdevenv-environment.clixml

      - uses: seanmiddleditch/gha-setup-vsdevenv@main
      
      # ...a bunch of steps...
      
      - uses: seanmiddleditch/gha-setup-vsdevenv@main
        with:
          host_arch: amd64
          toolset_version: 14.37.32822
          components: 'Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64;Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64'
          arch: arm64

      # ...more steps...

      # setup-vsdevenv doesn't properly overwrite an earlier setup.
      - name: Restore Windows environment
        if: ${{ matrix.os == 'windows-latest' }}
        run: Import-CliXml ./pre-vsdevenv-environment.clixml | % { Set-Item "env:$($_.Name)" $_.Value }
```

to work around it.
